# Generated by Django 4.2.20 on 2025-03-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='resume_path',
        ),
        migrations.AddField(
            model_name='registration',
            name='resume_telegram_link',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
