# .github/workflows/deploy.yml

name: Deploy to Production

on:
  push:
    branches: [ main ]
  # Manual trigger option
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug Environment
    run: |
      echo "Checking server connection details..."
      echo "Server Host Length: ${{ length(secrets.SERVER_HOST) }}"
      echo "Username Length: ${{ length(secrets.SERVER_USERNAME) }}"
      echo "Password Length: ${{ length(secrets.SERVER_PASSWORD) }}"
      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /var/www/hr-bot/
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput
          sudo systemctl restart hrbot
          sudo systemctl restart hrbot-bot
          sudo systemctl restart nginx
          echo "Deployment completed successfully!"