# .github/workflows/deploy.yml

name: Deploy to Production

on:
  push:
    branches: [ main ]
  # Manual trigger option
  workflow_dispatch:

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
  SSH_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Debug Environment
      run: |
        echo "Checking server connection details..."
        echo "Server Host Length: ${{ env.SERVER_HOST != '' && env.SERVER_HOST != null }}"
        echo "Username Length: ${{ env.SERVER_USERNAME != '' && env.SERVER_USERNAME != null }}"
        echo "Password Length: ${{ env.SERVER_PASSWORD != '' && env.SERVER_PASSWORD != null }}"
      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USERNAME }}
        password: ${{ env.SSH_PASSWORD }}
        port: 22
        script: |
          cd /var/www/hr-bot/
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput
          sudo systemctl restart hrbot.socket hrbot.service
          sudo systemctl restart hrbot-bot
          sudo systemctl restart nginx
          echo "Deployment completed successfully!"