# .github/workflows/deploy.yml

name: Deploy to Production

on:
  push:
    branches: [ main ]
  # Manual trigger option
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no -p 22 ${secrets.SERVER_USERNAME}@${secrets.SERVER_HOST} 'echo "SSH Connection Successful"'

    - name: Debug Environment
      run: |
        echo "Checking server connection details..."
        echo "Server Host Length: ${{ secrets.SERVER_HOST != '' && secrets.SERVER_HOST != null }}"
        echo "Username Length: ${{ secrets.SERVER_USERNAME != '' && secrets.SERVER_USERNAME != null }}"
        echo "Password Length: ${{ secrets.SERVER_PASSWORD != '' && secrets.SERVER_PASSWORD != null }}"
      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /var/www/hr-bot/
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput
          sudo systemctl restart hrbot.socket hrbot.service
          sudo systemctl restart hrbot-bot
          sudo systemctl restart nginx
          echo "Deployment completed successfully!"